### PR TITLE
Roche lobe: fixes and new model type

### PR DESCRIPTION
**Pull request by fabienbaron**
This adds a Roche lobe model based on fill factor. 
Also fixes minor issues with classic (r_pole based) Roche lobe model.

### CODE REVIEW

**Comment by fabienbaron** [comment]
Now also improved grid search output.

**Comment by bkloppenborg** [comment]
Could you make a few changes:
1. Please use spaces instead of tabs in the code.
2. For the Roche Lobe (Fill Factor) model, it appears R_pole is superfluous, it should be removed from being a parameter.

I'm not sure about the performance impact of printing data to the console for the grid search. This could result in a loss of performance as writing to the console is much more lengthy than most of SIMTOI's operations. What are your thoughts?

**Comment by bkloppenborg** [comment]
By the way, the auto_ptr -> unique_ptr change needed to be made in `ccoifits`. I just pushed that change upstream and propagated it down to SIMTOI's develop branch.

**Comment by bkloppenborg** [comment]
After discussions with Fabien on this PR, I will have to add a removeParameter function to the parameterMap class to fix item 2. I'll also fix item 1 at the same time.

**Pull request merged**
